name: elon-musk-ai-bot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - aiogram==3.4.1
      - python-dotenv==1.0.1
      - google-generativeai==0.5.2
      - redis==5.0.1
      - asyncio
